services:
    python:
        build:
            context: ./languages/python
    java:
        build:
            context: ./languages/java
    javascript:
        build:
            context: ./languages/javascript
    csharp:
        build:
            context: ./languages/csharp
    vb:
        build:
            context: ./languages/vb
    c:
        build:
            context: ./languages/c
    php:
        build:
            context: ./languages/php
    ruby:
        build:
            context: ./languages/ruby
    lua:
        build:
            context: ./languages/lua
    golang:
        build:
            context: ./languages/golang
    rust:
        build:
            context: ./languages/rust
